mm/feature/subscription
Interstellar-Lab/genqlient pull request #1
Opened 2023-08-24 08:10 UTC by matthieu4294967296moineau

# Feature
- first version supporting subscription

2023-08-29 15:03 UTC, jjauzion requested changes

2023-08-29 15:03 UTC, jjauzion commented on graphql/client.go
> +
Peut etre ajouter la doc vu que le makeRequest est documenté. Notamment pour expliquer le `dataUpdated`
 et les valeur de retour

2023-08-29 15:03 UTC, jjauzion commented on internal/integration/integration_test.go
> +	websocketClient := newRoundtripWebScoketClient(t, "ws"+strings.TrimPrefix(server.URL, "http"))
```suggestion
	websocketClient := newRoundtripWebScoketClient(t, server.URL)
```
pour garder un schéma identique aux autres RoundTrip et mettre le `"ws"+strings.TrimPrefix(server.URL, "http")` dans la fonction.
Et peut etre ajouter un check si les server.URL est déjà au format "ws://..."

2023-08-29 15:03 UTC, jjauzion commented on internal/integration/integration_test.go
> +	require.Errorf(t, err, "client does not support websocket")
```suggestion
	require.Errorf(t, err, "client does not support subscription")
```

2023-08-29 15:03 UTC, jjauzion commented on internal/integration/integration_test.go
> +	require.Errorf(t, err, "client does not support websocket")
```suggestion
	require.Errorf(t, err, "client does not support subscription")
```

2023-08-29 15:03 UTC, jjauzion commented on internal/integration/integration_test.go
> +				break
c'est redondant les deux non ?
Soit on met loop à false; soit on fait un break mais pas besoin des 2

2023-08-29 15:03 UTC, jjauzion commented on graphql/client.go
> +type Dialer interface {
add doc for Dialer & DialContext

2023-08-29 15:03 UTC, jjauzion commented on graphql/websocket.go
> +	defer endListenWebSocket(dataUpdated, errChan, done, err)
a quoi ça sert de passer la variable `err` ?
vu que `err` n'est pas un pointeur elle sera toujours = nil (la valeur est copié au moment ou tu crée le defer)

2023-08-29 15:03 UTC, jjauzion commented on graphql/websocket.go
> +	}
est-ce qu'il ne faudrait pas un timeout ?

2023-08-29 15:03 UTC, jjauzion commented on graphql/websocket.go
> +	}
et est-ce que ça ne serait pas mieux de faire le check du ACK dans le client plutot:
```
        [...]
	err = sendInit(conn)
	if err != nil {
		startedWithError <- err
		return
	}
	err = sendSubscribe(conn, req)
	if err != nil {
		startedWithError <- err
		return
	}
	startedWithError <- nil
        waitForConnAck(conn, errChan)

        go listenWebSocket(conn, resp, dataUpdated, errChan, done)

        waitToEndWebSocket(conn, errChan, done)
```

2023-08-29 15:03 UTC, jjauzion commented on internal/integration/generated.go
> +) (chan countWsResponse, chan struct{}, chan error, map[string]interface{}, error) {
peut etre utiliser des named param pour expliciter a quoi correspond le `chan struct{}`
```suggestion
) (dataChan chan countWsResponse, doneChan chan struct{}, errChan chan error, map[string]interface{}, err error) {
```

2023-08-29 15:03 UTC, jjauzion commented on internal/integration/generated.go
> +) (chan countWsResponse, chan struct{}, chan error, map[string]interface{}, error) {
et pourquoi ne pas plutot faire un `chan bool` plutot que `chan struct{}` ? 
Ca serait plus simple a comprendre quand on ferme la chan de faire:
```
defer func() { doneChan <- True }()
```
plutot que 
```
defer func() { doneChan <- struct{}{} }()
```

2023-08-29 15:03 UTC, jjauzion commented on graphql/client.go
> +	DialContext(ctx context.Context, urlStr string, requestHeader http.Header) (*websocket.Conn, *http.Response, error)
le type de la var retourné `*websocket.Conn` est une dépendance directe aux package `github.com/gorilla/websocket` donc l'utilisateur du package `genqlient` ne peut pas utiliser une autre implementation de websocket que celle là; je pense qu'ils auraient voulu une implementation plus agnositique.
Mais bon... pas facile a changer

2023-08-29 15:03 UTC, jjauzion commented on graphql/client.go
> +	go c.webSocketSubscriptionRoutine(
est-ce qu'on a vraiment besoin de lancer ça dans une go routine ? pour éviter d'avoir une go routine qui lance une go routine qui lance une go routine

J'ai l'impression qu'on a besoin que d'une go routine listenWebSocket()

2023-08-29 15:03 UTC, jjauzion commented on internal/integration/generated.go
> +	go countForwardData(dataChan_, resp_, dataUpdated_, errChan_)
plutot que de passer le pointeur vers resp_ a go routine de go routine qui met a jour la variable puis envoie un bool sur dataUpdated, est-ce qu'on ne peut pas plutot passer un `chan graphql.Response` a la go routine listenWebSocket() directement ? Voir même lui passer le dataChan_ et comme ça plus besoin du `go countForwardData(dataChan_, resp_, dataUpdated_, errChan_)`

2023-08-29 15:03 UTC, jjauzion commented on graphql/client.go
> +
mettre une fct `waitForConnAck(conn, errChan)` ici plutot que d'attendre le ConnAck dans le `listenWebSocket` ?

2023-08-29 15:03 UTC, jjauzion commented on internal/integration/generated.go
> +func count(
est-ce qu'on peut ajouter une doc ? surtout pour préciser qu'il faut faire un `defer doneChan <- True` pour bien fermer la connexion

2023-08-30 07:54 UTC, matthieu4294967296moineau commented on internal/integration/integration_test.go
> +	websocketClient := newRoundtripWebScoketClient(t, "ws"+strings.TrimPrefix(server.URL, "http"))
done

2023-08-30 07:56 UTC, matthieu4294967296moineau commented on internal/integration/integration_test.go
> +	require.Errorf(t, err, "client does not support websocket")
là c'est vraiment parce que le client n'utilise pas la bonne méthode

2023-08-30 07:56 UTC, matthieu4294967296moineau commented on internal/integration/integration_test.go
> +	require.Errorf(t, err, "client does not support websocket")
là c'est vraiment parce que le client n'utilise pas la bonne méthode

2023-08-30 07:57 UTC, matthieu4294967296moineau commented on internal/integration/integration_test.go
> +				break
le break nous sort du select, donc on a besoin des 2

2023-08-30 08:21 UTC, matthieu4294967296moineau commented on graphql/websocket.go
> +	defer endListenWebSocket(dataUpdated, errChan, done, err)
corrected using pointer

2023-08-30 08:30 UTC, matthieu4294967296moineau commented on graphql/websocket.go
> +	}
done

2023-08-30 09:52 UTC, matthieu4294967296moineau commented on internal/integration/generated.go
> +) (chan countWsResponse, chan struct{}, chan error, map[string]interface{}, error) {
done

2023-08-30 13:25 UTC, matthieu4294967296moineau commented on internal/integration/generated.go
> +	go countForwardData(dataChan_, resp_, dataUpdated_, errChan_)
je ne peux pas passer le dataChan car il depend de la structure à renvoyer, et si j'utilise la structure graphql.Response pour unmarshal, je recois une map et non plus une string json, et je ne peux pas l'utiliser en tant que struct que je voudrais retourner

2023-08-30 13:39 UTC, matthieu4294967296moineau commented on graphql/client.go
> +	go c.webSocketSubscriptionRoutine(
done

2023-08-30 13:39 UTC, matthieu4294967296moineau commented on graphql/client.go
> +
done

2023-08-30 14:33 UTC, matthieu4294967296moineau commented on graphql/client.go
> +	DialContext(ctx context.Context, urlStr string, requestHeader http.Header) (*websocket.Conn, *http.Response, error)
done

2023-08-30 15:04 UTC, matthieu4294967296moineau commented on graphql/client.go
> +
done

2023-08-30 15:22 UTC, matthieu4294967296moineau commented on graphql/client.go
> +type Dialer interface {
done

2023-08-30 15:52 UTC, matthieu4294967296moineau commented on internal/integration/generated.go
> +func count(
done

2023-09-01 09:52 UTC, jjauzion reviewed
comme discuté, voir si on peut simplifier la creation du client pour l'utilisateur en ayant juste a créer un websocket puis a le passer a la fct NewClientUsingWebSocket():
```
dialer := websocket.DefaultDialer
	dialer.TLSClientConfig = tlsConfig
	dialer.Proxy = http.ProxyFromEnvironment
	dialer.HandshakeTimeout = 45 * time.Second

	headers := http.Header{}
	headers.Add("oauth", "AAigH40dXmE6krt1RS9ZN4_NT9XAvWXWJiSiphk0CmadVqvCa2nwYQ0")

	//wsClient := graphql.WebSocketClient{Dialer: &MyDialer{Dialer: dialer}, Header: headers}
	graphqlClient := graphql.NewClientUsingWebSocket(
		"wss://localhost:8080/query",
		&dialer,
		header
	)
```

2023-09-01 09:52 UTC, jjauzion commented on graphql/client.go
> +	webSocketClient.doneChan = make(chan bool, 1)
doneChan unused

2023-09-04 08:44 UTC, jjauzion approved these changes
just need to add the example with subscription

2023-09-04 10:08 UTC, jjauzion approved these changes

2023-09-04 10:08 UTC, jjauzion commented on exampleSubscription/main.go
> +	graphqlClient.CloseWebSocket()
faire plutot un defer close après avoir créé le client ?

2023-09-04 11:56 UTC, matthieu4294967296moineau commented on exampleSubscription/main.go
> +	graphqlClient.CloseWebSocket()
done

2023-09-04 11:56 UTC, merged